const state={page:'dashboard',user:localStorage.getItem('sa_user')||'',students:JSON.parse(localStorage.getItem('sa_students')||'[]'),attendance:JSON.parse(localStorage.getItem('sa_attendance')||'[]')};
function save(){localStorage.setItem('sa_students',JSON.stringify(state.students));localStorage.setItem('sa_attendance',JSON.stringify(state.attendance));localStorage.setItem('sa_user',state.user)}
function today(){return new Date().toISOString().slice(0,10)}
function login(){const u=document.getElementById('u').value.trim(),p=document.getElementById('p').value;if(u&&p){state.user=u;save();render()}else alert('Enter username and password')}
function logout(){state.user='';save();render()}
function nav(p){state.page=p;render()}
function addStudent(){const roll=prompt('Roll number:');const name=prompt('Student name:');const cls=prompt('Class:','BCA');const sec=prompt('Section:','A');if(!roll||!name)return;if(state.students.some(s=>s.roll===roll)){alert('Roll number already exists');return}state.students.push({id:Date.now(),roll,name,cls,sec,active:true});save();render()}
function archive(id){const s=state.students.find(x=>x.id===id);if(s)s.active=!s.active;save();render()}
function mark(id){const d=today();if(state.attendance.some(a=>a.sid===id&&a.date===d)){alert('Attendance already marked today');return}const late=new Date().getHours()>=9&&new Date().getMinutes()>15?'Late':'Present';state.attendance.push({id:Date.now(),sid:id,date:d,time:new Date().toLocaleTimeString(),status:late,method:'System Camera Demo'});save();alert('Attendance marked: '+late);render()}
let stream=null;async function cameraStart(){try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});document.getElementById('video').srcObject=stream}catch(e){alert('Allow camera permission in browser. Use Chrome/Edge and localhost or HTTPS.')}}
function cameraStop(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null}
function capture(){const v=document.getElementById('video'),c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);document.getElementById('shot').src=c.toDataURL('image/jpeg');document.getElementById('shot').style.display='block'}
function reportRows(){return state.attendance.slice().reverse().map(a=>{const s=state.students.find(x=>x.id===a.sid)||{};return `<tr><td>${a.date}</td><td>${a.time}</td><td>${s.roll||''}</td><td>${s.name||''}</td><td>${s.cls||''}-${s.sec||''}</td><td><span class="badge ${a.status.toLowerCase()}">${a.status}</span></td><td>${a.method}</td></tr>`}).join('')}
function exportCSV(){let csv='Date,Time,Roll,Name,Class,Status,Method\n';state.attendance.forEach(a=>{const s=state.students.find(x=>x.id===a.sid)||{};csv+=`${a.date},${a.time},${s.roll||''},${s.name||''},${s.cls||''}-${s.sec||''},${a.status},${a.method}\n`});const blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='attendance_report.csv';a.click();URL.revokeObjectURL(url)}
function render(){if(!state.user){document.getElementById('app').innerHTML=`<div class="login"><div class="login-card"><h1>Smart Attendance</h1><p>Attendance Management System</p><input id="u" class="form-control" placeholder="Username"><input id="p" type="password" class="form-control" placeholder="Password"><button class="btn" style="width:100%" onclick="login()">Login</button><p class="muted">Demo login: any non-empty username and password</p></div></div>`;return}
const navs=[['dashboard','Dashboard'],['students','Students'],['camera','Live Camera'],['attendance','Attendance'],['reports','Reports'],['settings','Settings']];let body='';
if(state.page==='dashboard'){const active=state.students.filter(s=>s.active).length,present=state.attendance.filter(a=>a.date===today()&&a.status==='Present').length,late=state.attendance.filter(a=>a.date===today()&&a.status==='Late').length;body=`<div class="top"><div><h1>Dashboard</h1><p class="muted">Welcome, ${state.user}</p></div><button class="btn secondary" onclick="logout()">Logout</button></div><div class="cards"><div class="card"><div class="stat">${active}</div><div class="muted">Active Students</div></div><div class="card"><div class="stat">${present}</div><div class="muted">Present Today</div></div><div class="card"><div class="stat">${late}</div><div class="muted">Late Today</div></div><div class="card"><div class="stat">${state.attendance.length}</div><div class="muted">Total Records</div></div></div><div class="grid"><section class="panel"><h2>Quick Actions</h2><div class="actions"><button class="btn" onclick="nav('students')">Register Student</button><button class="btn" onclick="nav('camera')">Open Camera</button><button class="btn" onclick="nav('reports')">Reports</button></div></section><section class="panel"><h2>System</h2><p>Camera uses the computer's default/system camera through the browser. No external webcam is required.</p></section></div>`}
if(state.page==='students'){body=`<div class="top"><h1>Students</h1><button class="btn" onclick="addStudent()">+ Add Student</button></div><div class="panel"><div class="table-wrap"><table><tr><th>Roll</th><th>Name</th><th>Class</th><th>Status</th><th>Action</th></tr>${state.students.map(s=>`<tr><td>${s.roll}</td><td>${s.name}</td><td>${s.cls}-${s.sec}</td><td>${s.active?'Active':'Archived'}</td><td><button class="btn secondary" onclick="archive(${s.id})">${s.active?'Archive':'Restore'}</button></td></tr>`).join('')}</table></div></div>`}
if(state.page==='camera'){body=`<h1>Live Camera Attendance</h1><div class="notice">Uses the system/default camera. Allow camera permission in your browser.</div><div class="grid"><section class="panel"><div class="camera"><video id="video" autoplay playsinline></video></div><div class="actions" style="margin-top:10px"><button class="btn" onclick="cameraStart()">Start System Camera</button><button class="btn secondary" onclick="capture()">Capture</button><button class="btn secondary" onclick="cameraStop()">Stop</button></div><img id="shot" style="display:none;max-width:220px;margin-top:12px;border-radius:10px"></section><section class="panel"><h2>Mark Attendance</h2>${state.students.filter(s=>s.active).map(s=>`<div class="actions" style="justify-content:space-between;border-bottom:1px solid #eee;padding:10px 0"><span><b>${s.roll}</b> — ${s.name}</span><button class="btn" onclick="mark(${s.id})">Verify & Mark</button></div>`).join('')||'<p>No active students. Register one first.</p>'}</section></div>`}
if(state.page==='attendance'){body=`<h1>Attendance</h1><div class="panel"><div class="table-wrap"><table><tr><th>Date</th><th>Time</th><th>Roll</th><th>Name</th><th>Class</th><th>Status</th></tr>${reportRows().replaceAll('<td>${a.method}</td>','')}</table></div></div>`}
if(state.page==='reports'){body=`<div class="top"><h1>Reports</h1><button class="btn" onclick="exportCSV()">Export CSV</button></div><div class="panel"><div class="table-wrap"><table><tr><th>Date</th><th>Time</th><th>Roll</th><th>Name</th><th>Class</th><th>Status</th><th>Method</th></tr>${reportRows()}</table></div></div>`}
if(state.page==='settings'){body=`<h1>Settings</h1><div class="panel"><h2>Attendance Settings</h2><label>Late after</label><input class="form-control" value="09:15" disabled><p class="muted">This demo uses 09:15 as the late threshold. Production systems should store this securely in a backend.</p></div>`}
document.getElementById('app').innerHTML=`<div class="shell"><aside class="side"><div class="brand">Smart Attendance</div><div class="nav">${navs.map(n=>`<button class="${state.page===n[0]?'active':''}" onclick="nav('${n[0]}')">${n[1]}</button>`).join('')}</div></aside><section class="content">${body}</section></div>`}
render();
