const KEY='rag_attendance_v4';let data=JSON.parse(localStorage.getItem(KEY)||'null');let regDescriptor=null,streamMap={};
const defaults={morning:{start:'09:00',late:'09:15',end:'12:30'},afternoon:{start:'13:30',late:'13:45',end:'17:00'}};
if(!data)data={students:[],attendance:[],settings:defaults,rag:[{title:'Attendance Rule',text:'Morning and Afternoon are separate sessions. Start to Late After is Present; after Late After until End is Late. No attendance by session end is Absent.'},{title:'Duplicate Prevention',text:'A student can have only one attendance record per date and session.'},{title:'Proxy Prevention',text:'Attendance is accepted only after a registered face descriptor matches a student. Unknown faces are rejected.'}]};
function save(){localStorage.setItem(KEY,JSON.stringify(data));refresh()}
function login(){if(document.getElementById('user').value==='admin'&&document.getElementById('pass').value==='admin123'){sessionStorage.login='1';document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');refresh()}else alert('Invalid login')}
function logout(){sessionStorage.clear();location.reload()}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');refresh()}
async function loadModels(){if(window.modelsLoaded)return;document.getElementById('regStatus').textContent='Loading face model...';const url='https://justadudewhohacks.github.io/face-api.js/models';await faceapi.nets.tinyFaceDetector.loadFromUri(url);await faceapi.nets.faceLandmark68Net.loadFromUri(url);await faceapi.nets.faceRecognitionNet.loadFromUri(url);window.modelsLoaded=true;document.getElementById('regStatus').textContent='Face model ready.'}
async function startCam(id){try{await loadModels();if(streamMap[id])streamMap[id].getTracks().forEach(t=>t.stop());const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});document.getElementById(id).srcObject=s;streamMap[id]=s}catch(e){alert('Camera/model error. Allow camera permission and use Live Server or HTTPS.\n'+e.message)}}
async function getDescriptor(video){const r=await faceapi.detectSingleFace(video,new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceDescriptor();return r?r.descriptor:null}
async function captureRegister(){if(!document.getElementById('regVideo').srcObject)return alert('Start system camera first.');const d=await getDescriptor(document.getElementById('regVideo'));if(!d)return document.getElementById('regStatus').innerHTML='<div class="error">No clear face detected. Face the camera and try again.</div>';regDescriptor=Array.from(d);document.getElementById('regStatus').innerHTML='<div class="success">Face captured and descriptor created ✓</div>'}
function registerStudent(){const id=sid.value.trim(),name=sname.value.trim(),roll=window.roll.value.trim(),cls=window.cls.value.trim(),sec=window.sec.value.trim();if(!id||!name||!roll||!cls||!sec||!regDescriptor)return alert('Fill all details and capture face first.');if(data.students.some(s=>s.id===id||s.roll===roll))return alert('Student ID or Roll Number already exists.');data.students.push({id,roll,name,cls,sec,descriptor:regDescriptor,active:true});regDescriptor=null;['sid','sname','roll','cls','sec'].forEach(x=>document.getElementById(x).value='');save();alert('Student registered successfully with Face + ID.')}
async function verifyAttendance(){if(!document.getElementById('attVideo').srcObject)return alert('Start system camera first.');const d=await getDescriptor(document.getElementById('attVideo'));if(!d)return scanResult.innerHTML='<div class="error">Face not detected. Attendance rejected.</div>';let best=null,bestDist=1;for(const s of data.students.filter(x=>x.active&&x.descriptor)){const dist=faceapi.euclideanDistance(d,new Float32Array(s.descriptor));if(dist<bestDist){bestDist=dist;best=s}}if(!best||bestDist>0.48){scanResult.innerHTML='<div class="error">❌ Face not matched. Student not recognized. Attendance NOT marked.</div>';verifiedStudent.innerHTML='No verified student.';return}const sess=document.getElementById('session').value;const date=new Date().toISOString().slice(0,10);if(data.attendance.some(a=>a.studentId===best.id&&a.date===date&&a.session===sess)){scanResult.innerHTML='<div class="error">⚠️ Duplicate Attendance — already marked for this session.</div>';verifiedStudent.innerHTML=studentHTML(best);return}const rule=data.settings[sess.toLowerCase()],now=new Date(),mins=now.getHours()*60+now.getMinutes(),toMin=x=>{let [h,m]=x.split(':').map(Number);return h*60+m};let status;if(mins<toMin(rule.start)||mins>toMin(rule.end)){scanResult.innerHTML='<div class="error">Outside session time. Attendance rejected.</div>';return}status=mins<=toMin(rule.late)?'Present':'Late';data.attendance.push({studentId:best.id,date,time:now.toTimeString().slice(0,8),session:sess,status,confidence:Math.max(0,1-bestDist).toFixed(3)});save();verifiedStudent.innerHTML=studentHTML(best)+`<p><b>${status}</b> • ${sess} • Match distance ${bestDist.toFixed(3)}</p>`;scanResult.innerHTML=`<div class="success">✅ Face matched. Attendance marked <b>${status}</b>.</div>`}
function studentHTML(s){return `<div class="student"><b>${s.name}</b><br>ID: ${s.id}<br>Roll: ${s.roll}<br>Class: ${s.cls} - ${s.sec}</div>`}
function updateSessionHint(){const r=data.settings[session.value.toLowerCase()];sessionHint.textContent=`${r.start} start • ${r.late} late-after • ${r.end} end`}
function refresh(){studentCount.textContent=data.students.filter(s=>s.active).length;const d=new Date().toISOString().slice(0,10);const todays=data.attendance.filter(a=>a.date===d);todayCount.textContent=todays.length;presentCount.textContent=todays.filter(a=>a.status==='Present').length;lateCount.textContent=todays.filter(a=>a.status==='Late').length;studentList.innerHTML=data.students.map(s=>studentHTML(s)+`<span class="badge">${s.active?'Active':'Archived'}</span>`).join('')||'No students';month.value=month.value||d.slice(0,7);mStart.value=data.settings.morning.start;mLate.value=data.settings.morning.late;mEnd.value=data.settings.morning.end;aStart.value=data.settings.afternoon.start;aLate.value=data.settings.afternoon.late;aEnd.value=data.settings.afternoon.end;updateSessionHint();}
function saveSettings(){data.settings.morning={start:mStart.value,late:mLate.value,end:mEnd.value};data.settings.afternoon={start:aStart.value,late:aLate.value,end:aEnd.value};save();alert('Session settings saved.')}
function renderReport(){const mo=month.value;if(!mo)return;let html='<tr><th>Date</th><th>Student</th><th>Morning</th><th>Afternoon</th><th>Present</th><th>Late</th><th>Absent</th><th>%</th></tr>';for(const s of data.students){let days=new Set(data.attendance.filter(a=>a.studentId===s.id&&a.date.startsWith(mo)).map(a=>a.date));for(const day of days){let m=data.attendance.find(a=>a.studentId===s.id&&a.date===day&&a.session==='Morning'),a=data.attendance.find(a=>a.studentId===s.id&&a.date===day&&a.session==='Afternoon');let vals=[m?.status||'Absent',a?.status||'Absent'];let p=vals.filter(x=>x==='Present').length,l=vals.filter(x=>x==='Late').length,ab=vals.filter(x=>x==='Absent').length;html+=`<tr><td>${day}</td><td>${s.name}</td><td>${vals[0]}</td><td>${vals[1]}</td><td>${p}</td><td>${l}</td><td>${ab}</td><td>${Math.round((p+l/2)/2*100)}%</td></tr>`}}reportTable.innerHTML=html}
function exportCSV(){renderReport();const rows=[...reportTable.rows].map(r=>[...r.cells].map(c=>c.innerText));const csv=rows.map(r=>r.map(x=>'"'+x.replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='monthly_attendance.csv';a.click()}
function ragSearch(){const q=ragQuery.value.toLowerCase();const terms=q.split(/\s+/).filter(Boolean);const docs=[...data.rag,...data.students.map(s=>({title:s.name,text:`Student ${s.id} ${s.roll} ${s.cls} ${s.sec}. Attendance: `+data.attendance.filter(a=>a.studentId===s.id).map(a=>`${a.date} ${a.session} ${a.status}`).join(', ')}))];const scored=docs.map(d=>({d,score:terms.reduce((n,t)=>n+(d.title+' '+d.text).toLowerCase().includes(t)?1:0,0)})).filter(x=>x.score).sort((a,b)=>b.score-a.score);ragResults.innerHTML=scored.length?scored.map(x=>`<div class="student"><b>${x.d.title}</b><p>${x.d.text}</p><small>Relevance score: ${x.score}</small></div>`).join(''):'<div class="error">No relevant historical data found.</div>'}
if(sessionStorage.login){login()}window.addEventListener('beforeunload',()=>Object.values(streamMap).forEach(s=>s.getTracks().forEach(t=>t.stop())));
